name: test-ros-talker-listener-{name}
linux:
  auto:
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run snapcraft:"
      command: snapcraft
    - action: "Install the snap:"
      command: sudo snap install --devmode --dangerous *.snap
    - action: "List your installed snaps to confirm:"
      command: snap list
    - action: "Run the snap:"
      command: ${name} -h
    - warning: |
        Make sure the name matches what has been used previously (i.e <code>${name}</code>)
  manual:
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run the snapcraft Docker image:"
      command: docker run -v $PWD:$PWD -w $PWD snapcore/snapcraft snapcraft
    - action: "Install the snap:"
      command: sudo snap install --devmode --dangerous *.snap
    - action: "List your installed snaps to confirm:"
      command: snap list
    - action: "Run the snap:"
      command: ${name} -h
    - warning: |
        Make sure the name matches what has been used previously (i.e <code>${name}</code>)
macos:
  auto:
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run snapcraft:"
      command: snapcraft
  manual:
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run the snapcraft Docker image:"
      command: docker run -v $PWD:$PWD -w $PWD snapcore/snapcraft snapcraft
windows:
  auto:
    - action: Run Windows Subsystem for Linux from the Windows Start menu
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run snapcraft:"
      command: snapcraft
  manual:
    - action: "Return to the root directory of the project containing your snapcraft.yaml and run the snapcraft Docker image:"
      command: docker run -v $PWD:$PWD -w $PWD snapcore/snapcraft snapcraft
