name: ${name}
version: git
summary: Command line weather tool.
description: |
  Get current weather:-
    $ wethr
  Get current weather in metric units
    $ wethr --metric
  Get current weather in imperial units
    $ wethr --imperial

confinement: devmode
base: core18

parts:
  ${name}:
    plugin: nodejs
    source: .

apps:
  ${name}:
    command: wethr
